services:
  - type: worker
    name: rbsoft-autochat
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python rbsoft_auto_chat.py
    envVars:
      - key: RBSOFT_TOKEN
        sync: false
